### ISSUE TITLE
ImportError: No module named setuptools

### ISSUE THREAD

**Issue by DimitriMiranda** [alfakini/python-mercadobitcoin#20]
Ubuntu 18 
error 
ImportError: No module named setuptools

Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    from setuptools import setup
ImportError: No module named setuptools

**Comment by he7d3r** [comment]
@DimitriMiranda it should work once setuptools is installed on your system. E.g.:
```sudo apt-get install -y python-setuptools```
or
```sudo apt-get install -y python3-setuptools```
